--liquibase formatted sql

--changeset gdiaz:forums

insert  into `PET_FORUMS`(`ID`,`GUID`,`FORUM_NAME`,`ENCODED_NAME`,`FORUM_URL`,`PICTURE_URL`,`META_DESCRIPCION`,`META_KEYWORDS`,`FORUM_DESCRIPTION`) values (1,'0882cd3f94333e4a84e3665a6f224709','Chihuahua People','Chihuahua-People','http://www.chihuahua-people.com/','chihuahua-people.gif','An internet forum dedicated to the Chihuaua dog breed.','chihuahua, dog, breed, pet, forum, maillist','Welcome to Chihuahua-People.com - a Chihuahua website and forum. We have many features on this website to make your experience here more enjoyable. The first step would be to REGISTER for free so you can take advantage of all the features we have to offer.\n<ul>\n<li>\nChihuahua Forums - Our Chihuahua Forums with thousands of discussion topics.\n</li>\n<li>\nChihuahua Active Topics - Topics that are currently being discussed in the Forums.\n</li>\n<li>\nChihuahua Photo Gallery - Pictures posted by the Chihuahua-People.com membership.\n</li>\n<li>\nChihuahua Photo Contest - Submit your chihuahua to appear as our featured chi.\nChihuahua Breeders and Breeding - A forum for breeders and discussion about breeding.\n</li>\n</ul>');
insert  into `PET_FORUMS`(`ID`,`GUID`,`FORUM_NAME`,`ENCODED_NAME`,`FORUM_URL`,`PICTURE_URL`,`META_DESCRIPCION`,`META_KEYWORDS`,`FORUM_DESCRIPTION`) values (2,'4c62200eb3e2e3850590bbc9cd97dae4','GermanShepherds.com','GermanShepherds.com','http://www.germanshepherds.com/','german-shepherds-forum.jpg','A site focusing on the German Shepherd dog breed. It features photos, a discussion board, and breeding tips.','german, shepherd, dog, forum, breed, maillist, photos.','Welcome to GermanShepherds.com - a German Shepherd website and forum. This site is dedicated to all aspects of the German Shepherd Dog. The German Shepherd Dog is respected and admired throughout the world for its versatility, intelligence, and loyalty. This is their home. We have many features on this website to make your experience here more enjoyable. The first step would be to REGISTER for free so you can take advantage of all the features we have to offer.\n<ul>\n  <li>German Shepherd Forums - Our German Shepherd Forums with thousands of discussion topics.</li>\n  <li>German Shepherd Active Topics - Topics that are currently being discussed in the Forums.</li>\n  <li>German Shepherd Photo Gallery - Pictures posted by the GermanShepherds.com membership.</li>\n</ul>');
insert  into `PET_FORUMS`(`ID`,`GUID`,`FORUM_NAME`,`ENCODED_NAME`,`FORUM_URL`,`PICTURE_URL`,`META_DESCRIPCION`,`META_KEYWORDS`,`FORUM_DESCRIPTION`) values (3,'916637bb66ee91b0232baee44cb6f724','German Shepherd Home','German-Shepherd-Home','http://www.germanshepherdhome.net/','german-shepherd-home.png','A forum devoted to the German Shepherd dog breed. ','german, shepherd, dog, breed, forum, news, photos, discussion','This Forum is Privately Owned by Val under her Business name of One Tiger, LLC. Quite some time before February 2010 Val had thought about having a GSD forum. She was a Mod. and Admin. on another board that was good, but the owner of the board was an absentee owner which limited the things that the Admins. could do. The timing wasnâ€™t ever right so she continued to volunteer her time to that board. But in January of 2010 things changed on that other board and that bought about the â€œGerman Shepherd Homeâ€ forum.\n<br/>\nMission Statement for â€œGerman Shepherd Homeâ€.\n<br/>\nTo provide an on line community where ALL German Shepherd enthusiasts can gather,\nexchange ideas and information about breeding, training, health and behavior issues.\nTo support the rescue community and highlight their tireless efforts to help GSDs find a forever home.\n<br/>\nI hope you will feel this as â€œHomeâ€ just like many members already have.\n<br/>\nVal');
insert  into `PET_FORUMS`(`ID`,`GUID`,`FORUM_NAME`,`ENCODED_NAME`,`FORUM_URL`,`PICTURE_URL`,`META_DESCRIPCION`,`META_KEYWORDS`,`FORUM_DESCRIPTION`) values (4,'f417d6dbbdc84835fab14dfc04995f3d','Golden Retriever Forum','Golden-Retriever-Forum','http://www.goldenretrieverforum.com/','golden-retriever-forum.jpg','A pet forum devoted to the Golden Retriever dog breed','golden, retriever, forum, dog, breed, mail, comments','GoldenRetrieverForum.com is the premier Golden Retriever Dog Forum on the internet, with up to 30,000 members.\n<br/>\nRegistration is not mandatory, but registered users do not see some ads.');

--rollback DELETE FROM PET_FORUMS;