spring:
  profiles.active: default
---
spring:
  profiles: test
  datasource:
    url: jdbc:h2:file:~/testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      hbm2ddl.auto: create-drop
      ejb.naming_strategy: org.hibernate.cfg.EJB3NamingStrategy
    show_sql: true
---
spring:
  profiles: default
  datasource:
    url: jdbc:mysql://localhost:3306/canis-new
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      hbm2ddl.auto: none
      ejb.naming_strategy: org.hibernate.cfg.EJB3NamingStrategy
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show_sql: false